baseURL = "https://weyltensor007.github.io/"
languageCode = 'en-us'
title = "數學學思錄"
theme = 'beautifulhugo'
pygmentsStyle = "monokai"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true


[Params]
  mainSections = ["posts"] # 設置那些 content 下的 folder 要被渲染
  subtitle = "試著留下詳盡的推導吧!"
  rss = true
  hideAuthor = true
  comments = true
  defaultMode = "dark"
  showRelatedPosts = true # 要設為 true 才會在 tags/categories/series 頁面出現
  delayDisqus = true

[services]
  [services.disqus]
    shortname = 'github-io-tmqetc1x7e' # 要進去 disqus 平台查 shortname

[Params.author]
  email = "weyltensor@gmail.com"

[taxonomies]
  category = 'categories'
  series = 'series'
  tag = 'tags'

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 1


[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 1

[[menu.main]]
    name = "Categories"
    url = "categories"
    weight = 2

[[menu.main]]
    name = "Series"
    url = "series"
    weight = 3


# 需要這段才能正常渲染 <mark> tag
[markup.goldmark.renderer]
  unsafe = true

# TOC 顯示階層設定
[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false # ordered 代表用數字編號
    startLevel = 1